server:
  port: 5001
spring:
  datasource:
    url: ${TEST_POSTGRES_URL}
    username: ${TEST_POSTGRES_USERNAME}
    password: ${TEST_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db-changelog/changelog-master.xml
    enabled: true
aws:
  s3:
    access: ${S3_ACCESS}
    secret: ${S3_SECRET}
    region: ${S3_REGION}
    bucket: ${S3_BUCKET}
    url: ${S3_URL}