server:
  port: 5000
spring:
  datasource:
    url: ${TEST_POSTGRES_URL}
    username: ${TEST_POSTGRES_USERNAME}
    password: ${TEST_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # Set this based on your needs: validate, update, create, create-drop
    show-sql: true  # Show SQL queries in logs (optional)
    properties:
      hibernate:
        format_sql: true  # Format SQL queries for readability (optional) to access the H2 console
  liquibase:
    change-log: classpath:/db-changelog/changelog-master.xml # Path to your changelog master file
    enabled: true  # Enable Liquibase migrations